name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y sqlite3 libsqlite3-dev
        sudo apt-get install -y build-essential
        sudo apt-get install -y autoconf automake libtool
        git clone https://github.com/libcheck/check.git
        cd check
        autoreconf -fi
        ./configure
        make
        sudo make install
        sudo ldconfig
        sudo apt-get install -y python3-pip
        pip3 install subunit

    - name: Build project
      run: make

    - name: Run tests
      run: make test
